In [18]:


import numpy as np
import pandas as pd
  
mdnv_data = pd.read_excel("E:/Ingénierie 1 EISI/MSPR 1/Projet MSPR Big Data/Datasets/Used Datasets/Code_Com_Code_Departement-_Taux_pauvrete-base-cc-filosofi-2022.xlsx", sheet_name='COM')
mdnv_data

,Fichier Localisé Social et Fiscal (FiLoSoFi) - Année 2021,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,Communes et arrondissements municipaux,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Mise en ligne le 29/01/2024 Géographie a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,@Insee Source(s) : Insee-DGFIP-Cnaf-Cnav...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Code géographique,Libellé géographique,Nombre de ménages fiscaux,Nombre de personnes dans les ménages fiscaux,Médiane du niveau vie (€),Part des ménages fiscaux imposés (%),Taux de pauvreté-Ensemble (%),Taux de pauvreté-moins de 30 ans (%),Taux de pauvreté-30 à 39 ans (%),Taux de pauvreté-40 à 49 ans (%),...,"Part des pensions, retraites et rentes (%)",Part des revenus du patrimoine et autres reven...,Part de l'ensemble des prestations sociales (%),dont part des prestations familiales (%),dont part des minima sociaux (%),dont part des prestations logement (%),Part des impôts (%),1ᵉʳ décile du niveau de vie (€),9ᵉ décile du niveau de vie (€),Rapport interdécile 9ᵉ décile/1ᵉʳ décile
4,CODGEO,LIBGEO,NBMENFISC21,NBPERSMENFISC21,MED21,PIMP21,TP6021,TP60AGE121,TP60AGE221,TP60AGE321,...,PPEN21,PPAT21,PPSOC21,PPFAM21,PPMINI21,PPLOGT21,PIMPOT21,D121,D921,RD21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34919,97420,Sainte-Suzanne,8593,23979,17720,"31,0","34,0","50,0","41,0","34,0",...,"13,0","4,3","15,7","4,2","8,7","2,8","-12,1",9060,36230,"4,0"
34920,97421,Salazie,2472,6847,13280,"15,0","54,0",s,"57,0","55,0",...,"14,9","4,1","25,3","5,5","16,8","3,0","-8,7",6810,26240,"3,9"
34921,97422,Le Tampon,31239,79757,16560,"28,0","38,0","54,0","42,0","38,0",...,"19,7","7,0","16,8","4,1","9,4","3,3","-11,9",8660,35530,"4,1"
34922,97423,Les Trois-Bassins,2505,7019,16680,"27,0","37,0",s,"45,0","33,0",...,"14,6","4,3","15,8","3,7","10,2","1,9","-11,3",8570,33820,"3,9"
34923,97424,Cilaos,2142,5333,13780,"18,0","51,0",s,"53,0","58,0",...,"16,8","4,2","22,8","4,5","15,3","3,0","-9,4",7690,26690,"3,5"

In [19]:
new_col = mdnv_data.iloc[3]
mdnv_data.columns = new_col
mdnv_data

3,Code géographique,Libellé géographique,Nombre de ménages fiscaux,Nombre de personnes dans les ménages fiscaux,Médiane du niveau vie (€),Part des ménages fiscaux imposés (%),Taux de pauvreté-Ensemble (%),Taux de pauvreté-moins de 30 ans (%),Taux de pauvreté-30 à 39 ans (%),Taux de pauvreté-40 à 49 ans (%),...,"Part des pensions, retraites et rentes (%)",Part des revenus du patrimoine et autres revenus (%),Part de l'ensemble des prestations sociales (%),dont part des prestations familiales (%),dont part des minima sociaux (%),dont part des prestations logement (%),Part des impôts (%),1ᵉʳ décile du niveau de vie (€),9ᵉ décile du niveau de vie (€),Rapport interdécile 9ᵉ décile/1ᵉʳ décile
0,Communes et arrondissements municipaux,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Mise en ligne le 29/01/2024 Géographie a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,@Insee Source(s) : Insee-DGFIP-Cnaf-Cnav...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Code géographique,Libellé géographique,Nombre de ménages fiscaux,Nombre de personnes dans les ménages fiscaux,Médiane du niveau vie (€),Part des ménages fiscaux imposés (%),Taux de pauvreté-Ensemble (%),Taux de pauvreté-moins de 30 ans (%),Taux de pauvreté-30 à 39 ans (%),Taux de pauvreté-40 à 49 ans (%),...,"Part des pensions, retraites et rentes (%)",Part des revenus du patrimoine et autres reven...,Part de l'ensemble des prestations sociales (%),dont part des prestations familiales (%),dont part des minima sociaux (%),dont part des prestations logement (%),Part des impôts (%),1ᵉʳ décile du niveau de vie (€),9ᵉ décile du niveau de vie (€),Rapport interdécile 9ᵉ décile/1ᵉʳ décile
4,CODGEO,LIBGEO,NBMENFISC21,NBPERSMENFISC21,MED21,PIMP21,TP6021,TP60AGE121,TP60AGE221,TP60AGE321,...,PPEN21,PPAT21,PPSOC21,PPFAM21,PPMINI21,PPLOGT21,PIMPOT21,D121,D921,RD21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34919,97420,Sainte-Suzanne,8593,23979,17720,"31,0","34,0","50,0","41,0","34,0",...,"13,0","4,3","15,7","4,2","8,7","2,8","-12,1",9060,36230,"4,0"
34920,97421,Salazie,2472,6847,13280,"15,0","54,0",s,"57,0","55,0",...,"14,9","4,1","25,3","5,5","16,8","3,0","-8,7",6810,26240,"3,9"
34921,97422,Le Tampon,31239,79757,16560,"28,0","38,0","54,0","42,0","38,0",...,"19,7","7,0","16,8","4,1","9,4","3,3","-11,9",8660,35530,"4,1"
34922,97423,Les Trois-Bassins,2505,7019,16680,"27,0","37,0",s,"45,0","33,0",...,"14,6","4,3","15,8","3,7","10,2","1,9","-11,3",8570,33820,"3,9"
34923,97424,Cilaos,2142,5333,13780,"18,0","51,0",s,"53,0","58,0",...,"16,8","4,2","22,8","4,5","15,3","3,0","-9,4",7690,26690,"3,5"

In [24]:

mdnv_data = mdnv_data.drop(mdnv_data.index[:1])
mdnv_data.reset_index(drop=True)
mdnv_data

3,Code géographique,Libellé géographique,Nombre de ménages fiscaux,Nombre de personnes dans les ménages fiscaux,Médiane du niveau vie (€),Part des ménages fiscaux imposés (%),Taux de pauvreté-Ensemble (%),Taux de pauvreté-moins de 30 ans (%),Taux de pauvreté-30 à 39 ans (%),Taux de pauvreté-40 à 49 ans (%),...,"Part des pensions, retraites et rentes (%)",Part des revenus du patrimoine et autres revenus (%),Part de l'ensemble des prestations sociales (%),dont part des prestations familiales (%),dont part des minima sociaux (%),dont part des prestations logement (%),Part des impôts (%),1ᵉʳ décile du niveau de vie (€),9ᵉ décile du niveau de vie (€),Rapport interdécile 9ᵉ décile/1ᵉʳ décile
5,01001,L'Abergement-Clémenciat,346,895,25820,s,s,s,s,s,...,s,s,s,s,s,s,s,s,s,s
6,01002,L'Abergement-de-Varey,115,266,24480,s,s,s,s,s,...,s,s,s,s,s,s,s,s,s,s
7,01004,Ambérieu-en-Bugey,6855,15092,21660,"50,0","17,0","17,0","22,0","19,0",...,"25,3","10,2","7,0","2,6","3,0","1,4","-14,8",11890,36450,"3,1"
8,01005,Ambérieux-en-Dombes,800,2028,24610,"61,0",s,s,s,s,...,"21,4","10,0","3,4","2,1","0,9","0,4","-16,3",15560,40580,"2,6"
9,01006,Ambléon,51,107,24210,s,s,s,s,s,...,s,s,s,s,s,s,s,s,s,s
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34919,97420,Sainte-Suzanne,8593,23979,17720,"31,0","34,0","50,0","41,0","34,0",...,"13,0","4,3","15,7","4,2","8,7","2,8","-12,1",9060,36230,"4,0"
34920,97421,Salazie,2472,6847,13280,"15,0","54,0",s,"57,0","55,0",...,"14,9","4,1","25,3","5,5","16,8","3,0","-8,7",6810,26240,"3,9"
34921,97422,Le Tampon,31239,79757,16560,"28,0","38,0","54,0","42,0","38,0",...,"19,7","7,0","16,8","4,1","9,4","3,3","-11,9",8660,35530,"4,1"
34922,97423,Les Trois-Bassins,2505,7019,16680,"27,0","37,0",s,"45,0","33,0",...,"14,6","4,3","15,8","3,7","10,2","1,9","-11,3",8570,33820,"3,9"
34923,97424,Cilaos,2142,5333,13780,"18,0","51,0",s,"53,0","58,0",...,"16,8","4,2","22,8","4,5","15,3","3,0","-9,4",7690,26690,"3,5"

In [25]:
mdnv_data.columns.name = ""

In [26]:
mdnv_data = mdnv_data.reset_index(drop=True)

In [27]:
mdnv_data

,Code géographique,Libellé géographique,Nombre de ménages fiscaux,Nombre de personnes dans les ménages fiscaux,Médiane du niveau vie (€),Part des ménages fiscaux imposés (%),Taux de pauvreté-Ensemble (%),Taux de pauvreté-moins de 30 ans (%),Taux de pauvreté-30 à 39 ans (%),Taux de pauvreté-40 à 49 ans (%),...,"Part des pensions, retraites et rentes (%)",Part des revenus du patrimoine et autres revenus (%),Part de l'ensemble des prestations sociales (%),dont part des prestations familiales (%),dont part des minima sociaux (%),dont part des prestations logement (%),Part des impôts (%),1ᵉʳ décile du niveau de vie (€),9ᵉ décile du niveau de vie (€),Rapport interdécile 9ᵉ décile/1ᵉʳ décile
0,01001,L'Abergement-Clémenciat,346,895,25820,s,s,s,s,s,...,s,s,s,s,s,s,s,s,s,s
1,01002,L'Abergement-de-Varey,115,266,24480,s,s,s,s,s,...,s,s,s,s,s,s,s,s,s,s
2,01004,Ambérieu-en-Bugey,6855,15092,21660,"50,0","17,0","17,0","22,0","19,0",...,"25,3","10,2","7,0","2,6","3,0","1,4","-14,8",11890,36450,"3,1"
3,01005,Ambérieux-en-Dombes,800,2028,24610,"61,0",s,s,s,s,...,"21,4","10,0","3,4","2,1","0,9","0,4","-16,3",15560,40580,"2,6"
4,01006,Ambléon,51,107,24210,s,s,s,s,s,...,s,s,s,s,s,s,s,s,s,s
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34914,97420,Sainte-Suzanne,8593,23979,17720,"31,0","34,0","50,0","41,0","34,0",...,"13,0","4,3","15,7","4,2","8,7","2,8","-12,1",9060,36230,"4,0"
34915,97421,Salazie,2472,6847,13280,"15,0","54,0",s,"57,0","55,0",...,"14,9","4,1","25,3","5,5","16,8","3,0","-8,7",6810,26240,"3,9"
34916,97422,Le Tampon,31239,79757,16560,"28,0","38,0","54,0","42,0","38,0",...,"19,7","7,0","16,8","4,1","9,4","3,3","-11,9",8660,35530,"4,1"
34917,97423,Les Trois-Bassins,2505,7019,16680,"27,0","37,0",s,"45,0","33,0",...,"14,6","4,3","15,8","3,7","10,2","1,9","-11,3",8570,33820,"3,9"
34918,97424,Cilaos,2142,5333,13780,"18,0","51,0",s,"53,0","58,0",...,"16,8","4,2","22,8","4,5","15,3","3,0","-9,4",7690,26690,"3,5"

In [28]:
data = mdnv_data

In [29]:
needed_cols = ['Code géographique', 'Médiane du niveau vie (€)']

mdnv_data = mdnv_data.drop(columns=[col for col in mdnv_data.columns if col not in needed_cols])
mdnv_data

      Code géographique Médiane du niveau vie (€)
0                 01001                     25820
1                 01002                     24480
2                 01004                     21660
3                 01005                     24610
4                 01006                     24210
...                 ...                       ...
34914             97420                     17720
34915             97421                     13280
34916             97422                     16560
34917             97423                     16680
34918             97424                     13780

[34919 rows x 2 columns]

In [23]:
import os

rep_dir = "E:\Ingénierie 1 EISI\MSPR 1\Projet MSPR Big Data\Datasets\Extraxted Data"
if not os.path.exists(rep_dir):
    os.makedirs(rep_dir)
csv_file_dir = os.path.join(rep_dir, "mediane_niveau_vie.csv")
mdnv_data.to_csv(csv_file_dir, index=False)

In [30]:
needed_cols = ['Code géographique', 'Taux de pauvreté-Ensemble (%)']

tp_data = data.drop(columns=[col for col in data.columns if col not in needed_cols])
tp_data

      Code géographique Taux de pauvreté-Ensemble (%)
0                 01001                             s
1                 01002                             s
2                 01004                          17,0
3                 01005                             s
4                 01006                             s
...                 ...                           ...
34914             97420                          34,0
34915             97421                          54,0
34916             97422                          38,0
34917             97423                          37,0
34918             97424                          51,0

[34919 rows x 2 columns]

In [31]:
import os

rep_dir = "E:\Ingénierie 1 EISI\MSPR 1\Projet MSPR Big Data\Datasets\Extraxted Data"

csv_file_dir = os.path.join(rep_dir, "taux_pauvrete.csv")
tp_data.to_csv(csv_file_dir, index=False)