In [1]:
#Chargement du dataset
import pandas as pd

p2022 = pd.read_excel("E:/Ingénierie 1 EISI/MSPR 1/Projet MSPR Big Data/Datasets/Used Datasets/resultats-par-niveau-subcom-t1-france-entiere.xlsx")

In [2]:
p2022

,Code du département,Libellé du département,Code de la commune,Libellé de la commune,Etat saisie,Inscrits,Abstentions,% Abs/Ins,Votants,% Vot/Ins,...,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102
0,01,Ain,1,L'Abergement-Clémenciat,Complet,645,108,16.74,537,83.26,...,3,0.47,0.58,12,M,DUPONT-AIGNAN,Nicolas,21,3.26,4.04
1,01,Ain,2,L'Abergement-de-Varey,Complet,213,38,17.84,175,82.16,...,3,1.41,1.75,12,M,DUPONT-AIGNAN,Nicolas,0,0.00,0.00
2,01,Ain,4,Ambérieu-en-Bugey,Complet,8765,2078,23.71,6687,76.29,...,43,0.49,0.66,12,M,DUPONT-AIGNAN,Nicolas,181,2.07,2.76
3,01,Ain,5,Ambérieux-en-Dombes,Complet,1282,234,18.25,1048,81.75,...,2,0.16,0.19,12,M,DUPONT-AIGNAN,Nicolas,27,2.11,2.63
4,01,Ain,6,Ambléon,Complet,103,23,22.33,80,77.67,...,0,0.00,0.00,12,M,DUPONT-AIGNAN,Nicolas,1,0.97,1.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35240,ZZ,Français établis hors de France,229,Zurich,Complet,24868,14101,56.70,10767,43.30,...,47,0.19,0.44,12,M,DUPONT-AIGNAN,Nicolas,189,0.76,1.77
35241,ZZ,Français établis hors de France,231,Taipei,Complet,1709,942,55.12,767,44.88,...,10,0.59,1.32,12,M,DUPONT-AIGNAN,Nicolas,10,0.59,1.32
35242,ZZ,Français établis hors de France,233,Nour-Soultan,Complet,117,64,54.70,53,45.30,...,0,0.00,0.00,12,M,DUPONT-AIGNAN,Nicolas,1,0.85,1.96
35243,ZZ,Français établis hors de France,234,Monterrey,Complet,713,553,77.56,160,22.44,...,1,0.14,0.63,12,M,DUPONT-AIGNAN,Nicolas,1,0.14,0.63
35244,ZZ,Français établis hors de France,235,Bahamas (Nassau),Complet,136,78,57.35,58,42.65,...,0,0.00,0.00,12,M,DUPONT-AIGNAN,Nicolas,1,0.74,1.82

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
p2022

,Code du département,Libellé du département,Code de la commune,Libellé de la commune,Etat saisie,Inscrits,Abstentions,% Abs/Ins,Votants,% Vot/Ins,Blancs,% Blancs/Ins,% Blancs/Vot,Nuls,% Nuls/Ins,% Nuls/Vot,Exprimés,% Exp/Ins,% Exp/Vot,N°Panneau,Sexe,Nom,Prénom,Voix,% Voix/Ins,% Voix/Exp,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102
0,01,Ain,1,L'Abergement-Clémenciat,Complet,645,108,16.74,537,83.26,16,2.48,2.98,1,0.16,0.19,520,80.62,96.83,1,F,ARTHAUD,Nathalie,3,0.47,0.58,2,M,ROUSSEL,Fabien,6,0.93,1.15,3,M,MACRON,Emmanuel,150,23.26,28.85,4,M,LASSALLE,Jean,18,2.79,3.46,5,F,LE PEN,Marine,149,23.10,28.65,6,M,ZEMMOUR,Éric,43,6.67,8.27,7,M,MÉLENCHON,Jean-Luc,66,10.23,12.69,8,F,HIDALGO,Anne,5,0.78,0.96,9,M,JADOT,Yannick,30,4.65,5.77,10,F,PÉCRESSE,Valérie,26,4.03,5.00,11,M,POUTOU,Philippe,3,0.47,0.58,12,M,DUPONT-AIGNAN,Nicolas,21,3.26,4.04
1,01,Ain,2,L'Abergement-de-Varey,Complet,213,38,17.84,175,82.16,3,1.41,1.71,1,0.47,0.57,171,80.28,97.71,1,F,ARTHAUD,Nathalie,2,0.94,1.17,2,M,ROUSSEL,Fabien,7,3.29,4.09,3,M,MACRON,Emmanuel,50,23.47,29.24,4,M,LASSALLE,Jean,10,4.69,5.85,5,F,LE PEN,Marine,23,10.80,13.45,6,M,ZEMMOUR,Éric,14,6.57,8.19,7,M,MÉLENCHON,Jean-Luc,41,19.25,23.98,8,F,HIDALGO,Anne,3,1.41,1.75,9,M,JADOT,Yannick,10,4.69,5.85,10,F,PÉCRESSE,Valérie,8,3.76,4.68,11,M,POUTOU,Philippe,3,1.41,1.75,12,M,DUPONT-AIGNAN,Nicolas,0,0.00,0.00
2,01,Ain,4,Ambérieu-en-Bugey,Complet,8765,2078,23.71,6687,76.29,88,1.00,1.32,46,0.52,0.69,6553,74.76,98.00,1,F,ARTHAUD,Nathalie,38,0.43,0.58,2,M,ROUSSEL,Fabien,173,1.97,2.64,3,M,MACRON,Emmanuel,1453,16.58,22.17,4,M,LASSALLE,Jean,177,2.02,2.70,5,F,LE PEN,Marine,1646,18.78,25.12,6,M,ZEMMOUR,Éric,530,6.05,8.09,7,M,MÉLENCHON,Jean-Luc,1604,18.30,24.48,8,F,HIDALGO,Anne,112,1.28,1.71,9,M,JADOT,Yannick,287,3.27,4.38,10,F,PÉCRESSE,Valérie,309,3.53,4.72,11,M,POUTOU,Philippe,43,0.49,0.66,12,M,DUPONT-AIGNAN,Nicolas,181,2.07,2.76
3,01,Ain,5,Ambérieux-en-Dombes,Complet,1282,234,18.25,1048,81.75,14,1.09,1.34,6,0.47,0.57,1028,80.19,98.09,1,F,ARTHAUD,Nathalie,8,0.62,0.78,2,M,ROUSSEL,Fabien,19,1.48,1.85,3,M,MACRON,Emmanuel,279,21.76,27.14,4,M,LASSALLE,Jean,24,1.87,2.33,5,F,LE PEN,Marine,352,27.46,34.24,6,M,ZEMMOUR,Éric,77,6.01,7.49,7,M,MÉLENCHON,Jean-Luc,137,10.69,13.33,8,F,HIDALGO,Anne,14,1.09,1.36,9,M,JADOT,Yannick,41,3.20,3.99,10,F,PÉCRESSE,Valérie,48,3.74,4.67,11,M,POUTOU,Philippe,2,0.16,0.19,12,M,DUPONT-AIGNAN,Nicolas,27,2.11,2.63
4,01,Ain,6,Ambléon,Complet,103,23,22.33,80,77.67,3,2.91,3.75,0,0.00,0.00,77,74.76,96.25,1,F,ARTHAUD,Nathalie,0,0.00,0.00,2,M,ROUSSEL,Fabien,6,5.83,7.79,3,M,MACRON,Emmanuel,21,20.39,27.27,4,M,LASSALLE,Jean,2,1.94,2.60,5,F,LE PEN,Marine,16,15.53,20.78,6,M,ZEMMOUR,Éric,3,2.91,3.90,7,M,MÉLENCHON,Jean-Luc,15,14.56,19.48,8,F,HIDALGO,Anne,2,1.94,2.60,9,M,JADOT,Yannick,2,1.94,2.60,10,F,PÉCRESSE,Valérie,9,8.74,11.69,11,M,POUTOU,Philippe,0,0.00,0.00,12,M,DUPONT-AIGNAN,Nicolas,1,0.97,1.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35240,ZZ,Français établis hors de France,229,Zurich,Complet,24868,14101,56.70,10767,43.30,40,0.16,0.37,31,0.12,0.29,10696,43.01,99.34,1,F,ARTHAUD,Nathalie,26,0.10,0.24,2,M,ROUSSEL,Fabien,43,0.17,0.40,3,M,MACRON,Emmanuel,5756,23.15,53.81,4,M,LASSALLE,Jean,118,0.47,1.10,5,F,LE PEN,Marine,474,1.91,4.43,6,M,ZEMMOUR,Éric,726,2.92,6.79,7,M,MÉLENCHON,Jean-Luc,1475,5.93,13.79,8,F,HIDALGO,Anne,269,1.08,2.51,9,M,JADOT,Yannick,993,3.99,9.28,10,F,PÉCRESSE,Valérie,580,2.33,5.42,11,M,POUTOU,Philippe,47,0.19,0.44,12,M,DUPONT-AIGNAN,Nicolas,189,0.76,1.77
35241,ZZ,Français établis hors de France,231,Taipei,Complet,1709,942,55.12,767,44.88,8,0.47,1.04,2,0.12,0.26,757,44.29,98.70,1,F,ARTHAUD,Nathalie,2,0.12,0.26,2,M,ROUSSEL,Fabien,1,0.06,0.13,3,M,MACRON,Emmanuel,286,16.73,37.78,4,M,LASSALLE,Jean,11,0.64,1.45,5,F,LE PEN,Marine,29,1.70,3.83,6,M,ZEMMOUR,Éric,105,6.14,13.87,7,M,MÉLENCHON,Jean-Luc,176,10.30,23.25,8,F,HIDALGO,Anne,12,0.70,1.59,9,M,JADOT,Yannick,82,4.80,10.83,10,F,PÉCRESSE,Valérie,33,1.93,4.36,11,M,POUTOU,Philippe,10,0.59,1.32,12,M,DUPONT-AIGNAN,Nicolas,10,0.59,1.32
35242,ZZ,Français établis hors de France,233,Nour-Soultan,Complet,117,64,54.70,53,45.30,2,1.71,3.77,0,0.00,0.00,51,43.59,96.23,1,F,ARTHAUD,Nathalie,0,0.00,0.00,2,M,ROUSSEL,Fabien,1,0.85,1.96,3,M,MACRON,Emmanuel,25,21.37,49.02,4,M,LASSALLE,Jean,1,0.85,1.96,5,F,LE PEN,Marine,3,2.56,5.88,6,M,ZEMMOUR,Éric,7,5.98,13.73,7,M,MÉLENCHON,Jean-Luc,9,7.69,17.65,8,F,HIDALGO,Anne,0,0.00,0.00,9,M,JADOT,Yannick,4,3.42,7.84,10,F,PÉCRESSE,Valérie,0,0.00,0.00,11,M,POUTOU,Philippe,0,0.00,0.00,12,M,DUPONT-AIGNAN,Nicolas,1,0.85,1.96
35243,ZZ,Français établis hors de France,234,Monterrey,Complet,713,553,77.56,160,22.44,0,0.00,0.00,2,0.28,1.25,158,22.16,98.75,1,F,ARTHAUD,Nathalie,0,0.00,0.00,2,M,ROUSSEL,Fabien,1,0.14,0.63,3,M,MACRON,Emmanuel,96,13.46,60.76,4,M,LASSALLE,Jean,1,0.14,0.63,5,F,LE PEN,Marine,4,0.56,2.53,6,M,ZEMMOUR,Éric,18,2.52,11.39,7,M,MÉLENCHON,Jean-Luc,19,2.66,12.03,8,F,HIDALGO,Anne,2,0.28,1.27,9,M,JADOT,Yannick,10,1.40,6.33,10,F,PÉCRESSE,Valérie,5,0.70,3.16,11,M,POUTOU,Philippe,1,0.14,0.63,12,M,DUPONT-AIGNAN,Nicolas,1,0.14,0.63
35244,ZZ,Français établis hors de France,235,Bahamas (Nassau),Complet,136,78,57.35,58,42.65,3,2.21,5.17,0,0.00,0.00,55,40.44,94.83,1,F,ARTHAUD,Nathalie,0,0.00,0.00,2,M,ROUSSEL,Fabien,1,0.74,1.82,3,M,MACRON,Emmanuel,25,18.38,45.45,4,M,LASSALLE,Jean,0,0.00,0.00,5,F,LE PEN,Marine,3,2.21,5.45,6,M,ZEMMOUR,Éric,17,12.50,30.91,7,M,MÉLENCHON,Jean-Luc,2,1.47,3.64,8,F,HIDALGO,Anne,0,0.00,0.00,9,M,JADOT,Yannick,0,0.00,0.00,10,F,PÉCRESSE,Valérie,6,4.41,10.91,11,M,POUTOU,Philippe,0,0.00,0.00,12,M,DUPONT-AIGNAN,Nicolas,1,0.74,1.82

In [24]:
p2017

,Résultats par départements - Tour 1,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Code du département,Libellé du département,Inscrits,Abstentions,% Abs/Ins,Votants,% Vot/Ins,Blancs,% Blancs/Ins,% Blancs/Vot,Nuls,% Nuls/Ins,% Nuls/Vot,Exprimés,% Exp/Ins,% Exp/Vot,Sexe,Nom,Prénom,Voix,% Voix/Ins,% Voix/Exp,Sexe,Nom,Prénom,Voix,% Voix/Ins,% Voix/Exp,Sexe,Nom,Prénom,Voix,% Voix/Ins,% Voix/Exp,Sexe,Nom,Prénom,Voix,% Voix/Ins,% Voix/Exp,Sexe,Nom,Prénom,Voix,% Voix/Ins,% Voix/Exp,Sexe,Nom,Prénom,Voix,% Voix/Ins,% Voix/Exp,Sexe,Nom,Prénom,Voix,% Voix/Ins,% Voix/Exp,Sexe,Nom,Prénom,Voix,% Voix/Ins,% Voix/Exp,Sexe,Nom,Prénom,Voix,% Voix/Ins,% Voix/Exp,Sexe,Nom,Prénom,Voix,% Voix/Ins,% Voix/Exp,Sexe,Nom,Prénom,Voix,% Voix/Ins,% Voix/Exp
3,1,Ain,415886,81507,19.6,334379,80.4,6342,1.52,1.9,2238,0.54,0.67,325799,78.34,97.43,F,LE PEN,Marine,81455,19.59,25,M,MACRON,Emmanuel,73692,17.72,22.62,M,FILLON,François,69805,16.78,21.43,M,MÉLENCHON,Jean-Luc,51736,12.44,15.88,M,DUPONT-AIGNAN,Nicolas,19788,4.76,6.07,M,HAMON,Benoît,16711,4.02,5.13,M,ASSELINEAU,François,3612,0.87,1.11,M,LASSALLE,Jean,3465,0.83,1.06,M,POUTOU,Philippe,3098,0.74,0.95,F,ARTHAUD,Nathalie,1842,0.44,0.57,M,CHEMINADE,Jacques,595,0.14,0.18
4,2,Aisne,375752,80183,21.34,295569,78.66,5047,1.34,1.71,2382,0.63,0.81,288140,76.68,97.49,F,LE PEN,Marine,102770,27.35,35.67,M,MACRON,Emmanuel,51680,13.75,17.94,M,MÉLENCHON,Jean-Luc,48950,13.03,16.99,M,FILLON,François,46969,12.5,16.3,M,DUPONT-AIGNAN,Nicolas,14651,3.9,5.08,M,HAMON,Benoît,12230,3.25,4.24,M,POUTOU,Philippe,3156,0.84,1.1,F,ARTHAUD,Nathalie,2763,0.74,0.96,M,LASSALLE,Jean,2264,0.6,0.79,M,ASSELINEAU,François,2171,0.58,0.75,M,CHEMINADE,Jacques,536,0.14,0.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,ZP,Polynésie française,203940,124527,61.06,79413,38.94,1929,0.95,2.43,1862,0.91,2.34,75622,37.08,95.23,M,FILLON,François,26679,13.08,35.28,F,LE PEN,Marine,24604,12.06,32.54,M,MACRON,Emmanuel,11119,5.45,14.7,M,MÉLENCHON,Jean-Luc,5952,2.92,7.87,M,HAMON,Benoît,2203,1.08,2.91,M,DUPONT-AIGNAN,Nicolas,1767,0.87,2.34,M,ASSELINEAU,François,1206,0.59,1.59,M,POUTOU,Philippe,755,0.37,1,F,ARTHAUD,Nathalie,689,0.34,0.91,M,LASSALLE,Jean,447,0.22,0.59,M,CHEMINADE,Jacques,201,0.1,0.27
106,ZS,Saint-Pierre-et-Miquelon,4966,2238,45.07,2728,54.93,70,1.41,2.57,26,0.52,0.95,2632,53,96.48,M,MÉLENCHON,Jean-Luc,933,18.79,35.45,F,LE PEN,Marine,478,9.63,18.16,M,MACRON,Emmanuel,473,9.52,17.97,M,FILLON,François,261,5.26,9.92,M,HAMON,Benoît,217,4.37,8.24,M,DUPONT-AIGNAN,Nicolas,79,1.59,3,M,POUTOU,Philippe,64,1.29,2.43,M,LASSALLE,Jean,54,1.09,2.05,M,ASSELINEAU,François,36,0.72,1.37,F,ARTHAUD,Nathalie,28,0.56,1.06,M,CHEMINADE,Jacques,9,0.18,0.34
107,ZW,Wallis et Futuna,8464,3053,36.07,5411,63.93,35,0.41,0.65,28,0.33,0.52,5348,63.19,98.84,M,MACRON,Emmanuel,1630,19.26,30.48,M,FILLON,François,1526,18.03,28.53,M,HAMON,Benoît,1349,15.94,25.22,F,LE PEN,Marine,380,4.49,7.11,M,MÉLENCHON,Jean-Luc,192,2.27,3.59,M,DUPONT-AIGNAN,Nicolas,79,0.93,1.48,F,ARTHAUD,Nathalie,54,0.64,1.01,M,ASSELINEAU,François,50,0.59,0.93,M,POUTOU,Philippe,41,0.48,0.77,M,LASSALLE,Jean,29,0.34,0.54,M,CHEMINADE,Jacques,18,0.21,0.34
108,ZX,Saint-Martin/Saint-Barthélemy,25385,17202,67.76,8183,32.24,211,0.83,2.58,107,0.42,1.31,7865,30.98,96.11,M,FILLON,François,2518,9.92,32.02,F,LE PEN,Marine,1834,7.22,23.32,M,MACRON,Emmanuel,1572,6.19,19.99,M,MÉLENCHON,Jean-Luc,1153,4.54,14.66,M,HAMON,Benoît,247,0.97,3.14,M,DUPONT-AIGNAN,Nicolas,216,0.85,2.75,M,ASSELINEAU,François,112,0.44,1.42,M,POUTOU,Philippe,92,0.36,1.17,M,LASSALLE,Jean,68,0.27,0.86,F,ARTHAUD,Nathalie,35,0.14,0.45,M,CHEMINADE,Jacques,18,0.07,0.23
109,ZZ,Français établis hors de France,1264113,704383,55.72,559730,44.28,3169,0.25,0.57,2442,0.19,0.44,554119,43.83,99,M,MACRON,Emmanuel,223879,17.71,40.4,M,FILLON,François,145829,11.54,26.32,M,MÉLENCHON,Jean-Luc,87692,6.94,15.83,M,HAMON,Benoît,38092,3.01,6.87,F,LE PEN,Marine,35926,2.84,6.48,M,DUPONT-AIGNAN,Nicolas,8837,0.7,1.59,M,ASSELINEAU,François,5578,0.44,1.01,M,POUTOU,Philippe,3414,0.27,0.62,M,LASSALLE,Jean,2530,0.2,0.46,F,ARTHAUD,Nathalie,1312,0.1,0.24,M,CHEMINADE,Jacques,1030,0.08,0.19

In [5]:
#Les noms de colonnes manquants
cols_miss = ['Code du département', 'Libellé du département', 'Code de la commune', 'Libellé de la commune', 'Inscrits', 'Abstentions', '% Abs/Ins', 'Votants',	'% Vot/Ins', 'Blancs', '% Blancs/Ins', '% Blancs/Vot', 'Nuls', '% Nuls/Ins', '% Nuls/Vot', 'Exprimés', '% Exp/Ins','% Exp/Vot',	'N°Panneau', 'Sexe', 'Nom',	'Prénom', 'Voix', '% Voix/Ins',	'% Voix/Exp','N°Panneau','Sexe', 'Nom',	'Prénom', 'Voix', '% Voix/Ins',	'% Voix/Exp','N°Panneau','Sexe', 'Nom',	'Prénom', 'Voix', '% Voix/Ins',	'% Voix/Exp','N°Panneau','Sexe', 'Nom',	'Prénom', 'Voix', '% Voix/Ins',	'% Voix/Exp','N°Panneau','Sexe', 'Nom',	'Prénom', 'Voix', '% Voix/Ins',	'% Voix/Exp','N°Panneau','Sexe', 'Nom',	'Prénom', 'Voix', '% Voix/Ins',	'% Voix/Exp','N°Panneau','Sexe', 'Nom',	'Prénom', 'Voix', '% Voix/Ins',	'% Voix/Exp','N°Panneau','Sexe', 'Nom',	'Prénom', 'Voix', '% Voix/Ins',	'% Voix/Exp','N°Panneau','Sexe', 'Nom',	'Prénom', 'Voix', '% Voix/Ins',	'% Voix/Exp','N°Panneau','Sexe', 'Nom',	'Prénom', 'Voix', '% Voix/Ins',	'% Voix/Exp','N°Panneau','Sexe', 'Nom',	'Prénom', 'Voix', '% Voix/Ins',	'% Voix/Exp','N°Panneau','Sexe', 'Nom',	'Prénom', 'Voix', '% Voix/Ins',	'% Voix/Exp']

In [6]:
len(cols_miss)

102

In [7]:
p2022.columns = cols_miss

ValueError: Length mismatch: Expected axis has 103 elements, new values have 102 elements

In [8]:
p2022

,Code du département,Libellé du département,Code de la commune,Libellé de la commune,Etat saisie,Inscrits,Abstentions,% Abs/Ins,Votants,% Vot/Ins,Blancs,% Blancs/Ins,% Blancs/Vot,Nuls,% Nuls/Ins,% Nuls/Vot,Exprimés,% Exp/Ins,% Exp/Vot,N°Panneau,Sexe,Nom,Prénom,Voix,% Voix/Ins,% Voix/Exp,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102
0,01,Ain,1,L'Abergement-Clémenciat,Complet,645,108,16.74,537,83.26,16,2.48,2.98,1,0.16,0.19,520,80.62,96.83,1,F,ARTHAUD,Nathalie,3,0.47,0.58,2,M,ROUSSEL,Fabien,6,0.93,1.15,3,M,MACRON,Emmanuel,150,23.26,28.85,4,M,LASSALLE,Jean,18,2.79,3.46,5,F,LE PEN,Marine,149,23.10,28.65,6,M,ZEMMOUR,Éric,43,6.67,8.27,7,M,MÉLENCHON,Jean-Luc,66,10.23,12.69,8,F,HIDALGO,Anne,5,0.78,0.96,9,M,JADOT,Yannick,30,4.65,5.77,10,F,PÉCRESSE,Valérie,26,4.03,5.00,11,M,POUTOU,Philippe,3,0.47,0.58,12,M,DUPONT-AIGNAN,Nicolas,21,3.26,4.04
1,01,Ain,2,L'Abergement-de-Varey,Complet,213,38,17.84,175,82.16,3,1.41,1.71,1,0.47,0.57,171,80.28,97.71,1,F,ARTHAUD,Nathalie,2,0.94,1.17,2,M,ROUSSEL,Fabien,7,3.29,4.09,3,M,MACRON,Emmanuel,50,23.47,29.24,4,M,LASSALLE,Jean,10,4.69,5.85,5,F,LE PEN,Marine,23,10.80,13.45,6,M,ZEMMOUR,Éric,14,6.57,8.19,7,M,MÉLENCHON,Jean-Luc,41,19.25,23.98,8,F,HIDALGO,Anne,3,1.41,1.75,9,M,JADOT,Yannick,10,4.69,5.85,10,F,PÉCRESSE,Valérie,8,3.76,4.68,11,M,POUTOU,Philippe,3,1.41,1.75,12,M,DUPONT-AIGNAN,Nicolas,0,0.00,0.00
2,01,Ain,4,Ambérieu-en-Bugey,Complet,8765,2078,23.71,6687,76.29,88,1.00,1.32,46,0.52,0.69,6553,74.76,98.00,1,F,ARTHAUD,Nathalie,38,0.43,0.58,2,M,ROUSSEL,Fabien,173,1.97,2.64,3,M,MACRON,Emmanuel,1453,16.58,22.17,4,M,LASSALLE,Jean,177,2.02,2.70,5,F,LE PEN,Marine,1646,18.78,25.12,6,M,ZEMMOUR,Éric,530,6.05,8.09,7,M,MÉLENCHON,Jean-Luc,1604,18.30,24.48,8,F,HIDALGO,Anne,112,1.28,1.71,9,M,JADOT,Yannick,287,3.27,4.38,10,F,PÉCRESSE,Valérie,309,3.53,4.72,11,M,POUTOU,Philippe,43,0.49,0.66,12,M,DUPONT-AIGNAN,Nicolas,181,2.07,2.76
3,01,Ain,5,Ambérieux-en-Dombes,Complet,1282,234,18.25,1048,81.75,14,1.09,1.34,6,0.47,0.57,1028,80.19,98.09,1,F,ARTHAUD,Nathalie,8,0.62,0.78,2,M,ROUSSEL,Fabien,19,1.48,1.85,3,M,MACRON,Emmanuel,279,21.76,27.14,4,M,LASSALLE,Jean,24,1.87,2.33,5,F,LE PEN,Marine,352,27.46,34.24,6,M,ZEMMOUR,Éric,77,6.01,7.49,7,M,MÉLENCHON,Jean-Luc,137,10.69,13.33,8,F,HIDALGO,Anne,14,1.09,1.36,9,M,JADOT,Yannick,41,3.20,3.99,10,F,PÉCRESSE,Valérie,48,3.74,4.67,11,M,POUTOU,Philippe,2,0.16,0.19,12,M,DUPONT-AIGNAN,Nicolas,27,2.11,2.63
4,01,Ain,6,Ambléon,Complet,103,23,22.33,80,77.67,3,2.91,3.75,0,0.00,0.00,77,74.76,96.25,1,F,ARTHAUD,Nathalie,0,0.00,0.00,2,M,ROUSSEL,Fabien,6,5.83,7.79,3,M,MACRON,Emmanuel,21,20.39,27.27,4,M,LASSALLE,Jean,2,1.94,2.60,5,F,LE PEN,Marine,16,15.53,20.78,6,M,ZEMMOUR,Éric,3,2.91,3.90,7,M,MÉLENCHON,Jean-Luc,15,14.56,19.48,8,F,HIDALGO,Anne,2,1.94,2.60,9,M,JADOT,Yannick,2,1.94,2.60,10,F,PÉCRESSE,Valérie,9,8.74,11.69,11,M,POUTOU,Philippe,0,0.00,0.00,12,M,DUPONT-AIGNAN,Nicolas,1,0.97,1.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35240,ZZ,Français établis hors de France,229,Zurich,Complet,24868,14101,56.70,10767,43.30,40,0.16,0.37,31,0.12,0.29,10696,43.01,99.34,1,F,ARTHAUD,Nathalie,26,0.10,0.24,2,M,ROUSSEL,Fabien,43,0.17,0.40,3,M,MACRON,Emmanuel,5756,23.15,53.81,4,M,LASSALLE,Jean,118,0.47,1.10,5,F,LE PEN,Marine,474,1.91,4.43,6,M,ZEMMOUR,Éric,726,2.92,6.79,7,M,MÉLENCHON,Jean-Luc,1475,5.93,13.79,8,F,HIDALGO,Anne,269,1.08,2.51,9,M,JADOT,Yannick,993,3.99,9.28,10,F,PÉCRESSE,Valérie,580,2.33,5.42,11,M,POUTOU,Philippe,47,0.19,0.44,12,M,DUPONT-AIGNAN,Nicolas,189,0.76,1.77
35241,ZZ,Français établis hors de France,231,Taipei,Complet,1709,942,55.12,767,44.88,8,0.47,1.04,2,0.12,0.26,757,44.29,98.70,1,F,ARTHAUD,Nathalie,2,0.12,0.26,2,M,ROUSSEL,Fabien,1,0.06,0.13,3,M,MACRON,Emmanuel,286,16.73,37.78,4,M,LASSALLE,Jean,11,0.64,1.45,5,F,LE PEN,Marine,29,1.70,3.83,6,M,ZEMMOUR,Éric,105,6.14,13.87,7,M,MÉLENCHON,Jean-Luc,176,10.30,23.25,8,F,HIDALGO,Anne,12,0.70,1.59,9,M,JADOT,Yannick,82,4.80,10.83,10,F,PÉCRESSE,Valérie,33,1.93,4.36,11,M,POUTOU,Philippe,10,0.59,1.32,12,M,DUPONT-AIGNAN,Nicolas,10,0.59,1.32
35242,ZZ,Français établis hors de France,233,Nour-Soultan,Complet,117,64,54.70,53,45.30,2,1.71,3.77,0,0.00,0.00,51,43.59,96.23,1,F,ARTHAUD,Nathalie,0,0.00,0.00,2,M,ROUSSEL,Fabien,1,0.85,1.96,3,M,MACRON,Emmanuel,25,21.37,49.02,4,M,LASSALLE,Jean,1,0.85,1.96,5,F,LE PEN,Marine,3,2.56,5.88,6,M,ZEMMOUR,Éric,7,5.98,13.73,7,M,MÉLENCHON,Jean-Luc,9,7.69,17.65,8,F,HIDALGO,Anne,0,0.00,0.00,9,M,JADOT,Yannick,4,3.42,7.84,10,F,PÉCRESSE,Valérie,0,0.00,0.00,11,M,POUTOU,Philippe,0,0.00,0.00,12,M,DUPONT-AIGNAN,Nicolas,1,0.85,1.96
35243,ZZ,Français établis hors de France,234,Monterrey,Complet,713,553,77.56,160,22.44,0,0.00,0.00,2,0.28,1.25,158,22.16,98.75,1,F,ARTHAUD,Nathalie,0,0.00,0.00,2,M,ROUSSEL,Fabien,1,0.14,0.63,3,M,MACRON,Emmanuel,96,13.46,60.76,4,M,LASSALLE,Jean,1,0.14,0.63,5,F,LE PEN,Marine,4,0.56,2.53,6,M,ZEMMOUR,Éric,18,2.52,11.39,7,M,MÉLENCHON,Jean-Luc,19,2.66,12.03,8,F,HIDALGO,Anne,2,0.28,1.27,9,M,JADOT,Yannick,10,1.40,6.33,10,F,PÉCRESSE,Valérie,5,0.70,3.16,11,M,POUTOU,Philippe,1,0.14,0.63,12,M,DUPONT-AIGNAN,Nicolas,1,0.14,0.63
35244,ZZ,Français établis hors de France,235,Bahamas (Nassau),Complet,136,78,57.35,58,42.65,3,2.21,5.17,0,0.00,0.00,55,40.44,94.83,1,F,ARTHAUD,Nathalie,0,0.00,0.00,2,M,ROUSSEL,Fabien,1,0.74,1.82,3,M,MACRON,Emmanuel,25,18.38,45.45,4,M,LASSALLE,Jean,0,0.00,0.00,5,F,LE PEN,Marine,3,2.21,5.45,6,M,ZEMMOUR,Éric,17,12.50,30.91,7,M,MÉLENCHON,Jean-Luc,2,1.47,3.64,8,F,HIDALGO,Anne,0,0.00,0.00,9,M,JADOT,Yannick,0,0.00,0.00,10,F,PÉCRESSE,Valérie,6,4.41,10.91,11,M,POUTOU,Philippe,0,0.00,0.00,12,M,DUPONT-AIGNAN,Nicolas,1,0.74,1.82

In [9]:
#Concatenation du code département avec le code commune pour obtenir le code géographique
x = p2022['Code du département'].astype(str).str.zfill(2) + p2022['Code de la commune'].astype(str).str.zfill(3)

In [10]:
x

0        01001
1        01002
2        01004
3        01005
4        01006
         ...
35240    ZZ229
35241    ZZ231
35242    ZZ233
35243    ZZ234
35244    ZZ235
Length: 35245, dtype: object

In [11]:
p2022.iloc[:,0]

0        01
1        01
2        01
3        01
4        01
         ..
35240    ZZ
35241    ZZ
35242    ZZ
35243    ZZ
35244    ZZ
Name: Code du département, Length: 35245, dtype: object

In [12]:
i = 73
nom = p2022.iloc[:,i-4]

In [33]:
#Les colonnes Votants/Exprimés
colonnes_det = [25,32,39,46,53,60,67,74,81,88,95,102]

In [34]:
# Calculer le maximum des colonnes spécifiées pour chaque ligne
#max_par_ligne = p2022.iloc[:, colonnes_det].max(axis=1)
#max_par_ligne

In [35]:
# Calculer le maximum des colonnes spécifiées pour chaque ligne
max_par_ligne = p2022.iloc[:, colonnes_det].max(axis=1)
max_par_ligne

0        28.85
1        29.24
2        25.12
3        34.24
4        27.27
         ...
35240    53.81
35241    37.78
35242    49.02
35243    60.76
35244    45.45
Length: 35245, dtype: float64

In [36]:
# Calculer le maximum des colonnes spécifiées pour chaque ligne
max_par_ligne = p2022.iloc[:, colonnes_det].max(axis=1)

# Liste pour stocker les indices de colonnes correspondant à chaque maximum
col_det_de_chaque_max = []
elu_de_chaque_ligne = []

for index, row in p2022.iterrows():
    # Trouver l'indice de la colonne avec la valeur maximale pour cette ligne
    col_det = colonnes_det[row[colonnes_det].values.argmax()]
    # Ajouter l'indice à la liste et déterminer l'indice du candidat ayant la valeur maximale
    col_det_de_chaque_max.append(col_det)
    elu_de_chaque_ligne.append(col_det - 3)

In [37]:
elu_de_chaque_ligne

[36,
 36,
 50,
 50,
 36,
 50,
 50,
 36,
 50,
 50,
 64,
 50,
 64,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 64,
 36,
 64,
 36,
 50,
 36,
 50,
 50,
 50,
 36,
 36,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 36,
 36,
 50,
 50,
 50,
 50,
 36,
 50,
 36,
 36,
 50,
 36,
 64,
 50,
 50,
 50,
 36,
 36,
 36,
 50,
 36,
 50,
 36,
 36,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 36,
 36,
 50,
 50,
 50,
 36,
 64,
 36,
 50,
 36,
 50,
 50,
 50,
 36,
 50,
 36,
 36,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 36,
 36,
 36,
 50,
 50,
 50,
 50,
 50,
 64,
 50,
 50,
 36,
 50,
 50,
 36,
 36,
 36,
 36,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 36,
 36,
 50,
 64,
 50,
 36,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 36,
 50,
 50,
 36,
 36,
 50,
 64,
 36,
 50,
 64,
 50,
 36,
 50,
 50,
 50,
 36,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 36,
 50,
 36,
 50,
 50,
 36,
 64,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 50,
 36,
 50,
 36,
 36,
 36,
 36,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 36,
 50,
 36,
 36,
 50,
 64,
 50,
 36,
 36,
 36,
 36,
 36,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 64,
 50,
 50,
 36,
 50,
 36,
 36,
 50,
 50,
 50,
 36,
 50,
 50,
 36,
 50,
 36,
 36,
 36,
 50,
 50,
 36,
 36,
 64,
 36,
 50,
 50,
 50,
 50,
 36,
 36,
 50,
 36,
 50,
 50,
 36,
 50,
 50,
 36,
 50,
 36,
 36,
 50,
 50,
 36,
 36,
 50,
 36,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 36,
 36,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 36,
 36,
 36,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 36,
 50,
 50,
 36,
 36,
 50,
 50,
 36,
 36,
 36,
 50,
 50,
 36,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 36,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 36,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 22,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 22,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 36,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 64,
 50,
 50,
 50,
 36,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 36,
 50,
 36,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 64,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 57,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 36,
 50,
 ...]

In [38]:
# Créer une série à partir de la liste d'indices
les_elus = pd.Series(elu_de_chaque_ligne, index=p2022.index, name='index_des_elus')

In [39]:

les_elus.unique()

array([36, 50, 64, 22, 57, 43, 71, 85, 29, 78, 99], dtype=int64)

In [40]:
# Utiliser chaque valeur en tant qu'indice de colonne et chaque indice en tant qu'indice de ligne pour récupérer des valeurs
valeurs_recuperes = [p2022.iloc[index, col_det] for index, col_det in zip(les_elus.index, les_elus)]

In [41]:
len(valeurs_recuperes)

35245

In [42]:
#Le candidat élu par ligne (par commune)
data_elu = pd.Series(valeurs_recuperes, index=p2022.index, name='elu')

In [43]:
data_elu

0        Emmanuel
1        Emmanuel
2          Marine
3          Marine
4        Emmanuel
           ...
35240    Emmanuel
35241    Emmanuel
35242    Emmanuel
35243    Emmanuel
35244    Emmanuel
Name: elu, Length: 35245, dtype: object

In [44]:
x.columns = ['Code géographique','Elu']

In [45]:
df_elus = pd.DataFrame(x, columns=['Code géographique'])

In [46]:
df_elus

      Code géographique
0                 01001
1                 01002
2                 01004
3                 01005
4                 01006
...                 ...
35240             ZZ229
35241             ZZ231
35242             ZZ233
35243             ZZ234
35244             ZZ235

[35245 rows x 1 columns]

In [47]:
#Joindre le code géographique et le candidat élu par commune
df_elus['Elu'] = data_elu

In [48]:
df_elus

      Code géographique       Elu
0                 01001  Emmanuel
1                 01002  Emmanuel
2                 01004    Marine
3                 01005    Marine
4                 01006  Emmanuel
...                 ...       ...
35240             ZZ229  Emmanuel
35241             ZZ231  Emmanuel
35242             ZZ233  Emmanuel
35243             ZZ234  Emmanuel
35244             ZZ235  Emmanuel

[35245 rows x 2 columns]

In [49]:
candidats = df_elus['Elu'].unique()

In [50]:

candidats

array(['Emmanuel', 'Marine', 'Jean-Luc', 'Nathalie', 'Éric', 'Jean',
       'Anne', 'Valérie', 'Fabien', 'Yannick', 'Nicolas'], dtype=object)

In [54]:
#Classification des candidats selon leur orientation politique
# "EXG" pour extrême gauche
# "EXD" pour extrême droite
# "G" pour gauche
# "D" pour droite
# "c" pour centre


import numpy as np


conditions = [
    (df_elus['Elu'].isin(['Nathalie', 'Jean-Luc', 'Philippe'])),  # Condition 1
    (df_elus['Elu'].isin(['Anne', 'Yannick', 'Fabien'])),  # Condition 2
    (df_elus['Elu'].isin(['Emmanuel', 'Jean'])),  # Condition 3
    (df_elus['Elu'].isin(['Valérie', 'Nicolas'])),  # Condition 3
    (df_elus['Elu'].isin(['Éric', 'Marine']))   # Condition 5
]

df_elus['Orientation'] = np.select(conditions, ['EXG', 'G', 'C', 'D', 'EXD'], default='')


df_elus

      Code géographique       Elu Orientation
0                 01001  Emmanuel           C
1                 01002  Emmanuel           C
2                 01004    Marine         EXD
3                 01005    Marine         EXD
4                 01006  Emmanuel           C
...                 ...       ...         ...
35240             ZZ229  Emmanuel           C
35241             ZZ231  Emmanuel           C
35242             ZZ233  Emmanuel           C
35243             ZZ234  Emmanuel           C
35244             ZZ235  Emmanuel           C

[35245 rows x 3 columns]

In [55]:
#Enregistrement du Dataframe sous forme de fichier (.csv)

import os

rep_dir = "E:\Ingénierie 1 EISI\MSPR 1\Projet MSPR Big Data\Datasets\Extraxted Data"
if not os.path.exists(rep_dir):
    os.makedirs(rep_dir)
csv_file_dir = os.path.join(rep_dir, "EluEtOrientEX.csv")
df_elus.to_csv(csv_file_dir, index=False)

In [56]:
df_parti_elu = df_elus.drop('Elu', axis=1)
df_parti_elu

      Code géographique Orientation
0                 01001           C
1                 01002           C
2                 01004         EXD
3                 01005         EXD
4                 01006           C
...                 ...         ...
35240             ZZ229           C
35241             ZZ231           C
35242             ZZ233           C
35243             ZZ234           C
35244             ZZ235           C

[35245 rows x 2 columns]