In [1]:

import pandas as pd

df = pd.read_csv("E:/Ingénierie 1 EISI/MSPR 1/Projet MSPR Big Data/Datasets/Dataset to train/merged_dataset3.csv")

In [2]:
df

,Code géographique,Médiane du niveau vie (€),Taux d'activité des 15-64 ans,Taux d'emploi des 15-64 ans,Taux de chômage des 15-64 ans,Part des ouvriers dans les emplois,Coups et blessures volontaires,Vols avec armes,Cambriolages de logement,Vols de véhicules,Destructions et dégradations volontaires,Trafic de stupéfiants,Orientation
0,01001,25820,82.146767,76.795054,5.351713,13.591030,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,C
1,01002,24480,79.590630,78.142833,1.447797,20.695486,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,C
2,01004,21660,76.589365,66.277048,10.312316,24.024257,6.307326,0.000000,6.637090,3.054398,0.0,0.829401,EXD
3,01005,24610,81.244522,76.161262,5.083260,11.827352,0.000000,0.000000,13.028201,0.000000,0.0,0.000000,EXD
4,01006,24210,70.833333,63.888889,6.944444,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34804,95676,28540,82.900234,75.351423,7.548811,22.560221,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,C
34805,95678,30090,81.799802,76.015038,5.784763,27.358812,0.000000,0.000000,20.587511,0.000000,0.0,0.000000,C
34806,95680,16190,69.510790,55.603423,13.907367,20.568541,6.357330,0.201759,9.480884,3.484500,0.0,1.196702,EXG
34807,95682,24880,87.603306,80.991736,6.611570,28.415824,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,C
34808,95690,31810,82.606650,77.737189,4.869461,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,C

In [3]:
import pandas as pd

df_filtered = df.drop(df[df.eq(0).sum(axis=1) > 4].index)
df_filtered

,Code géographique,Médiane du niveau vie (€),Taux d'activité des 15-64 ans,Taux d'emploi des 15-64 ans,Taux de chômage des 15-64 ans,Part des ouvriers dans les emplois,Coups et blessures volontaires,Vols avec armes,Cambriolages de logement,Vols de véhicules,Destructions et dégradations volontaires,Trafic de stupéfiants,Orientation
2,01004,21660,76.589365,66.277048,10.312316,24.024257,6.307326,0.000000,6.637090,3.054398,0.0,0.829401,EXD
5,01007,24860,80.199921,74.109073,6.090848,26.468179,0.000000,0.000000,13.772014,5.085814,0.0,0.000000,EXD
21,01025,24880,80.076790,74.360873,5.715917,31.087892,0.246002,0.000000,6.532684,0.205002,0.0,0.000000,EXD
27,01031,20550,72.318436,61.470350,10.848086,38.346351,3.893770,0.000000,5.437850,0.780609,0.0,0.000000,EXD
28,01032,23060,78.848269,72.092889,6.755380,16.002283,2.186601,0.000000,18.432108,0.598180,0.0,0.000000,EXD
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34794,95628,29420,79.594423,72.750317,6.844106,16.818290,0.000000,0.000000,14.606954,5.269169,0.0,0.000000,C
34796,95637,25250,76.454519,67.759547,8.694972,9.793034,2.903853,0.000000,5.463193,3.270843,0.0,0.000000,EXG
34797,95641,25440,80.828727,72.797381,8.031346,36.867321,2.153948,0.000000,2.205220,6.357744,0.0,4.299015,EXD
34799,95652,27920,80.156223,73.892947,6.263276,9.879489,2.364964,0.000000,4.679735,3.625159,0.0,0.000000,EXD
34806,95680,16190,69.510790,55.603423,13.907367,20.568541,6.357330,0.201759,9.480884,3.484500,0.0,1.196702,EXG

In [4]:
cols_to_num = ['Code géographique', 'Médiane du niveau vie (€)', 'Taux d\'activité des 15-64 ans', 'Taux d\'emploi des 15-64 ans', 'Taux de chômage des 15-64 ans', 'Part des ouvriers dans les emplois', 'Coups et blessures volontaires', 'Vols avec armes', 'Cambriolages de logement', 'Vols de véhicules', 'Destructions et dégradations volontaires', 'Trafic de stupéfiants']

for col in cols_to_num:
    df_filtered[col] = pd.to_numeric(df_filtered[col], errors='coerce')

In [5]:
df_filtered = df_filtered.dropna()

In [6]:
cols_to_ver = ['Taux d\'activité des 15-64 ans', 'Taux d\'emploi des 15-64 ans', 'Taux de chômage des 15-64 ans', 'Part des ouvriers dans les emplois', 'Médiane du niveau vie (€)']
df_filtered = df_filtered.dropna(subset=cols_to_ver)

In [7]:
df_filtered

,Code géographique,Médiane du niveau vie (€),Taux d'activité des 15-64 ans,Taux d'emploi des 15-64 ans,Taux de chômage des 15-64 ans,Part des ouvriers dans les emplois,Coups et blessures volontaires,Vols avec armes,Cambriolages de logement,Vols de véhicules,Destructions et dégradations volontaires,Trafic de stupéfiants,Orientation
2,1004.0,21660,76.589365,66.277048,10.312316,24.024257,6.307326,0.000000,6.637090,3.054398,0.0,0.829401,EXD
5,1007.0,24860,80.199921,74.109073,6.090848,26.468179,0.000000,0.000000,13.772014,5.085814,0.0,0.000000,EXD
21,1025.0,24880,80.076790,74.360873,5.715917,31.087892,0.246002,0.000000,6.532684,0.205002,0.0,0.000000,EXD
27,1031.0,20550,72.318436,61.470350,10.848086,38.346351,3.893770,0.000000,5.437850,0.780609,0.0,0.000000,EXD
28,1032.0,23060,78.848269,72.092889,6.755380,16.002283,2.186601,0.000000,18.432108,0.598180,0.0,0.000000,EXD
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34794,95628.0,29420,79.594423,72.750317,6.844106,16.818290,0.000000,0.000000,14.606954,5.269169,0.0,0.000000,C
34796,95637.0,25250,76.454519,67.759547,8.694972,9.793034,2.903853,0.000000,5.463193,3.270843,0.0,0.000000,EXG
34797,95641.0,25440,80.828727,72.797381,8.031346,36.867321,2.153948,0.000000,2.205220,6.357744,0.0,4.299015,EXD
34799,95652.0,27920,80.156223,73.892947,6.263276,9.879489,2.364964,0.000000,4.679735,3.625159,0.0,0.000000,EXD
34806,95680.0,16190,69.510790,55.603423,13.907367,20.568541,6.357330,0.201759,9.480884,3.484500,0.0,1.196702,EXG

In [9]:

df_13 = df_filtered[~df_filtered['Code géographique'].astype(str).str.startswith('13')]
df_13

,Code géographique,Médiane du niveau vie (€),Taux d'activité des 15-64 ans,Taux d'emploi des 15-64 ans,Taux de chômage des 15-64 ans,Part des ouvriers dans les emplois,Coups et blessures volontaires,Vols avec armes,Cambriolages de logement,Vols de véhicules,Destructions et dégradations volontaires,Trafic de stupéfiants,Orientation
2,1004.0,21660,76.589365,66.277048,10.312316,24.024257,6.307326,0.000000,6.637090,3.054398,0.0,0.829401,EXD
5,1007.0,24860,80.199921,74.109073,6.090848,26.468179,0.000000,0.000000,13.772014,5.085814,0.0,0.000000,EXD
21,1025.0,24880,80.076790,74.360873,5.715917,31.087892,0.246002,0.000000,6.532684,0.205002,0.0,0.000000,EXD
27,1031.0,20550,72.318436,61.470350,10.848086,38.346351,3.893770,0.000000,5.437850,0.780609,0.0,0.000000,EXD
28,1032.0,23060,78.848269,72.092889,6.755380,16.002283,2.186601,0.000000,18.432108,0.598180,0.0,0.000000,EXD
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34794,95628.0,29420,79.594423,72.750317,6.844106,16.818290,0.000000,0.000000,14.606954,5.269169,0.0,0.000000,C
34796,95637.0,25250,76.454519,67.759547,8.694972,9.793034,2.903853,0.000000,5.463193,3.270843,0.0,0.000000,EXG
34797,95641.0,25440,80.828727,72.797381,8.031346,36.867321,2.153948,0.000000,2.205220,6.357744,0.0,4.299015,EXD
34799,95652.0,27920,80.156223,73.892947,6.263276,9.879489,2.364964,0.000000,4.679735,3.625159,0.0,0.000000,EXD
34806,95680.0,16190,69.510790,55.603423,13.907367,20.568541,6.357330,0.201759,9.480884,3.484500,0.0,1.196702,EXG

In [48]:
import os

rep_dir = "E:/Ingénierie 1 EISI/MSPR 1/Projet MSPR Big Data/Datasets/Dataset to pred"
if not os.path.exists(rep_dir):
    os.makedirs(rep_dir)
csv_file_dir = os.path.join(rep_dir, "Bouche_Du_Rhône(Par commune)EX.csv")
df_13.to_csv(csv_file_dir, index=False)

In [49]:

df_filtered = df_filtered[~df_filtered['Code géographique'].astype(str).str.startswith('13')]
df_filtered

,Code géographique,Médiane du niveau vie (€),Taux d'activité des 15-64 ans,Taux d'emploi des 15-64 ans,Taux de chômage des 15-64 ans,Part des ouvriers dans les emplois,Coups et blessures volontaires,Vols avec armes,Cambriolages de logement,Vols de véhicules,Destructions et dégradations volontaires,Trafic de stupéfiants,Orientation
0,1001.0,25820.0,82.146767,76.795054,5.351713,13.591030,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,C
1,1002.0,24480.0,79.590630,78.142833,1.447797,20.695486,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,C
2,1004.0,21660.0,76.589365,66.277048,10.312316,24.024257,6.307326,0.000000,6.637090,3.054398,0.0,0.829401,EXD
3,1005.0,24610.0,81.244522,76.161262,5.083260,11.827352,0.000000,0.000000,13.028201,0.000000,0.0,0.000000,EXD
5,1007.0,24860.0,80.199921,74.109073,6.090848,26.468179,0.000000,0.000000,13.772014,5.085814,0.0,0.000000,EXD
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34803,95675.0,25940.0,82.412286,76.351998,6.060288,41.619970,0.000000,0.000000,0.000000,3.898198,0.0,0.000000,EXD
34804,95676.0,28540.0,82.900234,75.351423,7.548811,22.560221,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,C
34805,95678.0,30090.0,81.799802,76.015038,5.784763,27.358812,0.000000,0.000000,20.587511,0.000000,0.0,0.000000,C
34806,95680.0,16190.0,69.510790,55.603423,13.907367,20.568541,6.357330,0.201759,9.480884,3.484500,0.0,1.196702,EXG
34807,95682.0,24880.0,87.603306,80.991736,6.611570,28.415824,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,C

In [10]:
df_filtered = df_filtered.drop(columns='Code géographique', axis=1)

In [11]:
X = df_filtered.drop(columns=['Orientation'])
y = df_filtered['Orientation']

In [13]:
y.value_counts()

C      1946
EXD    1683
EXG     396
G         1
Name: Orientation, dtype: int64

In [14]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model = LogisticRegression(multi_class='multinomial', solver='lbfgs')

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')


print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy: 0.6476426799007444
Precision: 0.6553701095750968
Recall: 0.5535224211326911
F1 Score: 0.5745972267111973

In [17]:
from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)
print("Rapport de classification LogisticRegression :")
print(report)

Rapport de classification LogisticRegression :
              precision    recall  f1-score   support

           C       0.68      0.73      0.70       370
         EXD       0.61      0.66      0.64       343
         EXG       0.68      0.27      0.38        93

    accuracy                           0.65       806
   macro avg       0.66      0.55      0.57       806
weighted avg       0.65      0.65      0.64       806